### PR TITLE
Update scene_file_writer.py

### PR DESCRIPTION
**Pull request by purusharths**
Added `input_file_path: './media/'` option in `CONFIG` dict

`manim --livestream` was giving the following error:
```
(manimations) [jarwin:~/Documents/envs]$ manim --livestream
Media will be stored in ./media/. You can change this behavior by writing a different directory to media_dir.txt.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/jarwin/Documents/envs/manimations/lib/python3.7/site-packages/manimlib/stream_starter.py", line 38, in __new__                                                                                                                
    return Scene(**kwargs)
  File "/home/jarwin/Documents/envs/manimations/lib/python3.7/site-packages/manimlib/scene/scene.py", line 37, in __init__                                                                                                                  
    self, **self.file_writer_config,
  File "/home/jarwin/Documents/envs/manimations/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 43, in __init__                                                                                                      
    self.init_output_directories()
  File "/home/jarwin/Documents/envs/manimations/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 48, in init_output_directories                                                                                       
    output_directory = self.output_directory or self.get_default_output_directory()
  File "/home/jarwin/Documents/envs/manimations/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 79, in get_default_output_directory                                                                                  
    filename = os.path.basename(self.input_file_path)
AttributeError: 'SceneFileWriter' object has no attribute 'input_file_path'

Manim is now running in streaming mode. Stream animations by passing
them to manim.play(), e.g.
>>> c = Circle()
>>> manim.play(ShowCreation(c))
 
```
To avoid the AttributeError, `input_file_path` was defined at the `CONFIG` dictionary.
After the changes to the same, no error was observed

### CODE REVIEW

**Comment by eulertour** [comment]
`input_file_path` is actually supposed to be the path to the module containing the scene being rendered
https://github.com/3b1b/manim/blob/1da185953c2a0109fe5f3b789e43d33b4d31a0bf/manimlib/config.py#L168
It makes sense that it isn't there when doing a livestream, so I would rather just let it be unset and let `get_default_output_directory` return none in that case.

**Comment by Kolloom** [comment]
is livestream strictly livestream? ( as in no file is stored locally ) For a while I thought livestream is like an interactive prompt

**Comment by eulertour** [comment]
Yes, when the livestreaming worked it didn't create a temporary file. It seems this functionality was broken in https://github.com/3b1b/manim/pull/418. I'll have to go back through and see how to make it work with Manim now.

**Comment by sebusca38** [comment]
hello good, I have the same error mun try to see if everything was installed correctly to occupy manim, but when I try to run the example scene I see the following, I just updated today the manim
`Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/blancos/Escritorio/herramaientas/manim/manimlib/stream_starter.py", line 38, in __new__
    return Scene(**kwargs)
  File "/home/blancos/Escritorio/herramaientas/manim/manimlib/scene/scene.py", line 37, in __init__
    self, **self.file_writer_config,
  File "/home/blancos/Escritorio/herramaientas/manim/manimlib/scene/scene_file_writer.py", line 44, in __init__
    self.init_output_directories()
  File "/home/blancos/Escritorio/herramaientas/manim/manimlib/scene/scene_file_writer.py", line 49, in init_output_directories
    module_directory = self.output_directory or self.get_default_module_directory()
  File "/home/blancos/Escritorio/herramaientas/manim/manimlib/scene/scene_file_writer.py", line 95, in get_default_module_directory
    filename = os.path.basename(self.input_file_path)
AttributeError: 'SceneFileWriter' object has no attribute 'input_file_path'

Manim is now running in streaming mode. Stream animations by passing
them to manim.play(), e.g.
>>> c = Circle()
>>> manim.play(ShowCreation(c))

>>> 
`

**Comment by TonyCrane** [comment]
The livestream mode has already been removed. So I'm closing this.
