### ISSUE TITLE
partially initialized module 'manimlib.config'

### ISSUE THREAD

**Issue by Lolshh** [3b1b/manim#1492]
### Describe the error
Hello, when I try to run the following code I get "ImportError: cannot import name 'get_custom_config' from partially initialized module 'manimlib.config'"

This is the code I run : 

```
from manim.imports import *

class SequencePlot(GraphScene):
    def __init__(self, **kwargs):
        GraphScene.__init__(
            self,
            y_axis_label=r"Concentration [\%]",
            x_axis_label="Time [s]",
            **kwargs
        )

    def construct(self):
        x = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101]
        y = [114, 171, 286, 401, 630, 744, 974, 1088, 1317, 1661, 1776, 2119, 2349, 2463, 2692, 3036, 3380, 3495, 3838, 4068, 4182, 4526, 4755, 5099, 5557, 5786]
        self.setup_axes()
        for i in range(len(x)):
            dot = Dot().move_to(self.coords_to_point(x[i], y[i]))
            self.add(dot)
```

This is the error : 

_Traceback (most recent call last):
  File "/Users/Cours/opt/anaconda3/bin/manim", line 5, in <module>
    from manimlib import main
  File "/Users/Cours/opt/anaconda3/lib/python3.8/site-packages/manimlib/__init__.py", line 2, in <module>
    import manimlib.config
  File "/Users/Cours/opt/anaconda3/lib/python3.8/site-packages/manimlib/config.py", line 6, in <module>
    from manimlib.config import get_custom_config
ImportError: cannot import name 'get_custom_config' from partially initialized module 'manimlib.config' (most likely due to a circular import) (/Users/Cours/opt/anaconda3/lib/python3.8/site-packages/manimlib/config.py)_

I work on MacOS Big Sur with python 3.8.

Could someone explain to me what's wrong and how could I fix it?

Thanks a lot !

**Comment by Leoriem-code** [comment]
In the same directory as the one you work in, try to type `manimlib --config`, maybe that will help.

**Comment by TonyCrane** [comment]
Use `manimgl code.py` in terminal instead of `manim code.py`. You confused version and usage.
